spring.application.name=email_service
server.port=8083


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# Connection settings
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.template.receive-timeout=10000
spring.rabbitmq.template.reply-timeout=10000

# Listener settings
spring.rabbitmq.listener.type=simple
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=3
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.default-requeue-rejected=false


spring.rabbitmq.template.exchange=user.exchange
spring.security.filter.order=10


spring.mail.username=serfvaler456@gmail.com
spring.mail.password=tacxxmrlcarstmxr
spring.mail.host=smtp.gmail.com
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
