spring.application.name=user_service
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_platform_users
spring.datasource.username=postgres
spring.datasource.password=12345


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false



spring.cloud.vault.uri=https://localhost:8200
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Ссылка на секрет из Vault
jwt.secret.access=${spring.cloud.vault.kv.secret.jwt-secrets.access-key}
jwt.secret.refresh=${spring.cloud.vault.kv.secret.jwt-secrets.refresh-key}