spring.application.name=user_service
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_platform_users
spring.datasource.username=postgres
spring.datasource.password=12345



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.url=jdbc:postgresql://localhost:5432/food_delivery_platform_users
spring.flyway.user=postgres
spring.flyway.password=12345
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


spring.cloud.vault.uri=https://localhost:8200
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Ссылка на секрет из Vault
jwt.secret.access=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyy=
jwt.secret.refresh=zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s8=*


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/

# Connection settings
spring.rabbitmq.connection-timeout=5000
spring.rabbitmq.template.receive-timeout=10000
spring.rabbitmq.template.reply-timeout=10000

# Listener settings
spring.rabbitmq.listener.type=simple
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.prefetch=1
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.max-concurrency=3
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.default-requeue-rejected=false


spring.rabbitmq.template.exchange=user.exchange
spring.security.filter.order=10


rabit.queue.name