spring.application.name=user_service
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery_platform_users
spring.datasource.username=postgres
spring.datasource.password=12345



spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.url=jdbc:postgresql://localhost:5432/food_delivery_platform_users
spring.flyway.user=postgres
spring.flyway.password=12345
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true


spring.cloud.vault.uri=https://localhost:8200
spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret

# Ссылка на секрет из Vault
jwt.secret.access=qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
jwt.secret.refresh=zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==